# Markdown
# markdown: redcarpet
markdown: kramdown
kramdown:
 parse_span_html: true
 coderay_line_numbers: inline
 syntax_highlighter: coderay
highlighter: rouge

# Outputting
permalink: /archives/:title/
timezone: America/New_York
paginate_path: "journal/page:num"
paginate: 10


plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-paginate
  - jekyll-assets
  - autoprefixer-rails
  - jekyll-seo-tag

exclude: [Gemfile, README.md, legacy, deploy, node_modules, yarn.lock, package.json]

# pager: 5
# pager_path: "journal/page"
# pager_category: "journal"

# domain: mattsheehan.me
# description: The web hub of all things Matt

contact:
mailing_address: 1620 Sturbridge Dr. Louisville OH 44641
phone: 330-614-1599
email: dev@mattsheehan.me
lang: en_US

# Plugin: jekyll-feed
title: Matthew Sheehan
author: "Matt Sheehan"
tagline: "Web home of Matt Sheehan"
description: ""
url: https://mattsheehan.me
twitter:
  username: MattSheehanDev
  card: summary
social:
  name: Matt Sheehan
  links:
    - https://www.github.com/sheehamj13
    - https://www.linkedin.com/in/matt-sheehan-4b209259/
    - https://www.goodreads.com/matt_sheehan
    - https://twitter.com/MattSheehanDev

# rss_title: Matt Sheehan
# rss_author: Matt Sheehan
# rss_description: The spiritual home of Matt Sheehan
# rss_link: http://www.mattsheehan.me

## Don't use system-wide less installation
# lessc: "node /usr/local/bin/lessc"
# lessc: "./node_modules/less/bin/lessc"
css_dest: assets/css

## Don't use system-wide ts installation
# tsc: "tsc"
tsc: "./node_modules/typescript/bin/tsc"
js_dest: assets/script


autoprefixer:
  browsers:
  - "cover 99.5%"


collections:
 pinned:
  output: false

defaults:
 - scope:
    type: posts
   values:
    layout: post
 - scope:
    type: pinned
    path: "journal"
   values:
    layout: post
 - scope:
    path: "about"
    type: pages
   values:
    layout: "about"
 - scope:
    path: "archives"
    type: "pages"
   values:
    layout: "default"
