name: Matthew Sheehan
author: "Matt Sheehan"
# markdown: redcarpet
markdown: kramdown
kramdown:
 parse_span_html: true
 coderay_line_numbers: inline
 syntax_highlighter: coderay
#  enable_coderay: true
highlighter: rouge
permalink: /archives/:title/

# url: "mattsheehan.me"

# pager: 5
# pager_path: "journal/page"
# pager_category: "journal"
plugins: [jekyll-admin, jekyll-paginate]
# gems: [jekyll-paginate]

paginate: 10
paginate_path: "journal/page:num"

# domain: mattsheehan.me
# description: The web hub of all things Matt

contact:
mailing_address: 1620 Sturbridge Dr. Louisville OH 44641
phone: 330-614-1599
email: dev@mattsheehan.me

rss_title: Matt Sheehan
rss_author: Matt Sheehan
rss_description: The spiritual home of Matt Sheehan
rss_link: http://www.mattsheehan.me

## Don't use system-wide less installation
# lessc: "node /usr/local/bin/lessc"
lessc: "./node_modules/less/bin/lessc"
css_dest: assets/css

## Don't use system-wide ts installation
# tsc: "tsc"
tsc: "./node_modules/typescript/bin/tsc"
js_dest: assets/script


exclude: [Gemfile, README.md, legacy, deploy, node_modules]

collections:
 pinned:
  output: false
 resume:
  output: false


defaults:
 - scope:
    type: posts
   values:
    layout: post
 - scope:
    type: pinned
    path: "journal"
   values:
    layout: post
 - scope:
    path: "about"
    type: pages
   values:
    layout: "default"
 - scope:
    path: "archives"
    type: "pages"
   values:
    layout: "default"
 # - scope:
 #    type: resume
 #    path: "resume/education"
 #   values:
 #    categories: "education"
 # - scope:
 #    type: resume
 #    path: "resume/work"
 #   values:
 #    categories: "job"
 # - scope:
 #    type: resume
 #    path: "resume/other"
 #   values:
 #    categories: "other"
