#!/bin/bash


# SSH/SFTP deployment
# Transfers site files from localhost to the remote server
# on a digital ocean droplet


# First we're going to ssh in to create the appropriate directories,
# before we sftp in and copy any files
ssh matt@192.81.213.200 '\
cd /var/www/www.mattsheehan.me/public_html;\
create_dir(){ if [ ! -d $1 ]; then mkdir $1; fi };\
create_dir 404;\
create_dir about;\
create_dir archives;\
create_dir assets;\
create_dir feeds;\
create_dir ietemplates;\
create_dir journal;\
create_dir projects;'


# Then we're going to sftp in and use the put command to copy files from localhost
# to the remote server
# The reason that we are not recursively copying _site is that we don't want to create
# the _site folder on the remote machine
sftp matt@192.81.213.200 <<EOF
cd /var/www/www.mattsheehan.me/public_html
put /home/matt/Dropbox/projects/mattsheehan/mattsheehan.me/_site/index.html
put /home/matt/Dropbox/projects/mattsheehan/mattsheehan.me/_site/robots.txt
put /home/matt/Dropbox/projects/mattsheehan/mattsheehan.me/_site/humans.txt

put -r /home/matt/Dropbox/projects/mattsheehan/mattsheehan.me/_site/404
put -r /home/matt/Dropbox/projects/mattsheehan/mattsheehan.me/_site/about
put -r /home/matt/Dropbox/projects/mattsheehan/mattsheehan.me/_site/archives
put -r /home/matt/Dropbox/projects/mattsheehan/mattsheehan.me/_site/assets
put -r /home/matt/Dropbox/projects/mattsheehan/mattsheehan.me/_site/feeds
put -r /home/matt/Dropbox/projects/mattsheehan/mattsheehan.me/_site/ietemplates
put -r /home/matt/Dropbox/projects/mattsheehan/mattsheehan.me/_site/journal
put -r /home/matt/Dropbox/projects/mattsheehan/mattsheehan.me/_site/projects
EOF
